### ISSUE TITLE
Help! Program running error reported

### ISSUE THREAD

**Issue by csf2022scut** [krransby/colony-counter#1]
Hello, I encountered the following error while running the code. How should I resolve it? Also, may I ask what version of OpenCV you are using?
Traceback (most recent call last):
  File "E:\bacterial count\colony-counter-main\counter.py", line 530, in <module>
    main(['counter.py', 'plate2.jpg', 'w'])
  File "E:\bacterial count\colony-counter-main\counter.py", line 506, in main
    img_ori, img_pro = preprocess_image(img_ori)
  File "E:\bacterial count\colony-counter-main\counter.py", line 89, in preprocess_image
    plate_mask, circle = find_plate(img_ori, img_bin)
  File "E:\bacterial count\colony-counter-main\counter.py", line 183, in find_plate
    radius_scale = cv2.getTrackbarPos('Plate Radius', window_name) / 100
cv2.error: OpenCV(4.8.1) D:\a\opencv-python\opencv-python\opencv\modules\highgui\src\window_w32.cpp:2561: error: (-27:Null pointer) NULL window: 'Plate Identification' in function 'cvGetTrackbarPos'

**Comment by krransby** [comment]
Hello, 

Apologies for the late reply here.

This code was written on Python 3.8.18 with the following requirements:
- numpy 1.20.1
- OpenCV 4.5.1.48

I have just pushed 45ffca3a826e74f7af21a8da2ffe21461707e075 which updates the "Prerequisites" section of the README to the above. It also adds a pip requirements.txt for easier installation.

Looking at the traceback, it seems like reverting back to OpenCV 4.5.1 from 4.8.1 could potentially fix this issue. Have a go and let me know if that works for you.

**Comment by csf2022scut** [comment]
> Hello,
> 
> Apologies for the late reply here.
> 
> This code was written on Python 3.8.18 with the following requirements:
> 
> * numpy 1.20.1
> * OpenCV 4.5.1.48
> 
> I have just pushed [45ffca3](https://github.com/krransby/colony-counter/commit/45ffca3a826e74f7af21a8da2ffe21461707e075) which updates the "Prerequisites" section of the README to the above. It also adds a pip requirements.txt for easier installation.
> 
> Looking at the traceback, it seems like reverting back to OpenCV 4.5.1 from 4.8.1 could potentially fix this issue. Have a go and let me know if that works for you.

Thanks for your reply!I still encounter some problems now, such as the GUI interface being limited by the screen size and blocked by the navigation bar. Also, how to proceed to the next step after selecting the recognition range? (Pressing the Q key does not respond)
![捕获](https://github.com/krransby/colony-counter/assets/117445516/9d5eaadf-65f7-43f8-8956-655b2622739e)

**Comment by krransby** [comment]
Hello,

f2ec5371ca39958ee1069e594c071ead94abf739 has just been pushed, which changes the following:
- The window / GUI *should* now scale to fit your screen size
- The code now allows for any key press, rather than restricting to q / Q only.

This update comes with some additional requirements - please make sure you run the following command again after pulling: `pip install -r requirements.txt`.

>**Please Note:** Due to limitations with OpenCV's window scaling, the resolution of your images will be limited to whichever of the following is smallest:
>- The original size of the image
>- 980 pixels
>- The smallest dimension of all of displays currently connected to the system.
>
>This is due to the fact that OpenCV's window size is dependent on the resolution of the image passed to `cv2.imshow()`.
>
>Note that the original results were achieved with a static scale of 980.

Have a go with this new version and let me know if it worked or if there are any additional problems.

**Comment by krransby** [comment]
Closing issue on 2024-05-06
